if(NOT DEFINED TOOL OR NOT DEFINED FIXTURES OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "TOOL, FIXTURES, and OUTPUT are required")
endif()

function(run_timed limit_ms)
  set(args ${ARGN})
  string(TIMESTAMP started "%s")
  execute_process(COMMAND "${TOOL}" ${args}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
  string(TIMESTAMP finished "%s")
  math(EXPR elapsed_ms "(${finished} - ${started}) * 1000")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Query failed: ${args}; output=${output}; error=${error}")
  endif()
  string(JSON schema ERROR_VARIABLE json_error GET "${output}" schema_version)
  if(json_error)
    message(FATAL_ERROR "Invalid JSON for ${args}: ${json_error}")
  endif()
  if(elapsed_ms GREATER limit_ms)
    message(FATAL_ERROR "Query exceeded ${limit_ms} ms: ${elapsed_ms} ms; ${args}")
  endif()
  if("${args}" MATCHES "symbol-origin")
    string(JSON source_scan GET "${output}" query_performance source_scan_ms)
    if(NOT source_scan EQUAL 0)
      message(FATAL_ERROR "symbol-origin performed a source scan")
    endif()
  endif()
endfunction()

run_timed(5000 type-info TCSEDatabase --index "${FIXTURES}/diagnose-v600.jdi" --include-inherited --include-overloads --format json)
run_timed(10000 symbol-origin TCSEOLEDBRowset --index "${FIXTURES}/diagnose-v600.jdi" --no-source-scan --format json)
run_timed(10000 diagnose --file "${FIXTURES}/DiagnosticCalls.pas" --line 15 --error-code E2010 --index "${FIXTURES}/diagnose-v600.jdi" --left-index "${FIXTURES}/diagnose-v500.jdi" --unit-map "${FIXTURES}/diagnostic-unit-map.json" --format json)
run_timed(10000 legacy-refs --file "${FIXTURES}/LegacyRefs.pas" --legacy-unit UVariStd --left-index "${FIXTURES}/diagnose-v500.jdi" --right-index "${FIXTURES}/diagnose-v600.jdi" --unit-map "${FIXTURES}/diagnostic-unit-map.json" --format json)
run_timed(10000 model-migration --file "${FIXTURES}/ModelMigration.pas" --symbol TCSFields --left-index "${FIXTURES}/diagnose-v500.jdi" --right-index "${FIXTURES}/diagnose-v600.jdi" --format json)
run_timed(30000 batch-diagnose --input "${FIXTURES}/batch-diagnose.json" --index "${FIXTURES}/diagnose-v600.jdi" --left-index "${FIXTURES}/diagnose-v500.jdi" --unit-map "${FIXTURES}/diagnostic-unit-map.json" --output "${OUTPUT}" --format json)
